# Generated by Django 2.2.13 on 2021-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
