# Generated by Django 3.1.7 on 2021-07-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210723_0320'),
        ('account', '0009_auto_20210723_1328'),
    ]

    operations = [
    ]
