# Generated by Django 3.1.7 on 2021-07-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210723_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
