# Generated by Django 3.1.7 on 2021-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_account_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_seller',
            field=models.BooleanField(),
        ),
    ]
